# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  build123d = {
    pname = "build123d";
    version = "v0.5.0";
    src = fetchFromGitHub {
      owner = "gumyr";
      repo = "build123d";
      rev = "v0.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-0ztJeKRmIWJeaF3Os8bydTN2wKV0ca6WTsKj5sLksPg=";
    };
  };
}
